In [1]:
import pandas as pd

In [84]:
approved_permits = pd.read_csv('approvedpermits.csv')
approved_permits.head()

/var/folders/4h/2q1v376n4mqc0vz5g1f00mbw0000gn/T/ipykernel_1775/3363746989.py:1: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  approved_permits = pd.read_csv('approvedpermits.csv')

,permitnumber,worktype,permittypedescr,description,comments,applicant,declared_valuation,total_fees,issued_date,expiration_date,...,address,city,state,zip,property_id,parcel_id,gpsy,gpsx,geom_point_2249,geom_point_4326
0,A1000569,INTEXT,Amendment to a Long Form,Interior/Exterior Work,This work is to Amend Permit ALT347244. Elimin...,Patrick Sharkey,"$36,500.00",$390.00,2021-01-28 16:29:26+00,2021-07-28 04:00:00+00,...,181-183 State ST,Boston,MA,2109.00,130392.00,303807000.00,2956234.65,777000.47,0101000020C9080000014080EF50B6274128B89653E58D...,0101000020E6100000A703291D63C351C074AD05ECF92D...
1,A100071,COB,Amendment to a Long Form,City of Boston,Change connector link layout from attached enc...,Renee Santeusanio,"$40,000.00",$29.00,2011-11-04 15:04:58+00,2012-05-04 04:00:00+00,...,175 W Boundary RD,West Roxbury,MA,2132.00,17268.00,2012032000.00,2920239.25,751016.12,0101000020C908000081DB363D50EB264164AA649F9747...,0101000020E61000005F23793993C951C071ECAA3E6021...
2,A1001012,OTHER,Amendment to a Long Form,Other,Amend Alt943748 to erect a roof deck as per pl...,Jusimar Oliveria,"$5,000.00",$70.00,2020-06-01 18:08:47+00,NaN,...,15 Prospect ST,Charlestown,MA,2129.00,113443.00,202837000.00,2962078.12,775710.38,0101000020C90800007E6BD6C23CAC2741422F500F4F99...,0101000020E6100000F053B47AAFC351C0A6BB62F20730...
3,A1001201,INTEXT,Amendment to a Long Form,Interior/Exterior Work,Build steel balcony over garden level with sta...,Andreas Hwang,"$74,295.75",$803.00,2019-11-13 18:38:56+00,2020-05-13 04:00:00+00,...,211 W Springfield ST,Roxbury,MA,2118.00,129994.00,402558000.00,2949422.57,769648.31,0101000020C9080000025726A0E07C274183505E499780...,0101000020E6100000D72A24D322C551C044521DC4982B...
4,A100137,EXTREN,Amendment to a Long Form,Renovations - Exterior,Landscaping/stonework - amending permit #2801/...,NaN,"$15,000.00",$182.00,2013-01-03 19:13:09+00,2013-07-03 04:00:00+00,...,14 William Jackson AVE,Brighton,MA,2135.00,149852.00,2204944000.00,2950790.70,749690.30,0101000020C9080000FCFDFA98F4E02641F6694F594383...,0101000020E61000009DED6FF7DBC951C0929A5BD71B2C...

In [85]:
#Cleaning stuff - Still have more to clean. Seems more manually though
approved_permits['city'] = approved_permits['city'].str.lower()
# approved_permits['city'] = approved_permits['city'].str.replace(' ', '', regex=False)
approved_permits['city'] = approved_permits['city'].str.replace('/boston', '', regex=False)
approved_permits['city'] = approved_permits['city'].str.replace('boston/', '', regex=False)
approved_permits['city'] = approved_permits['city'].str.replace(r'[\!\"\#\$\%\&\*\+\,\-\.\/\:;\<\=\>\?\@\[\\\]\^\_\`\{\|\}\~\']+$', '', regex=True)

approved_permits['declared_valuation'] = approved_permits['declared_valuation'].str.replace(r'[\$,]', '', regex=True)
approved_permits['declared_valuation'] = approved_permits['declared_valuation'].astype(float)

In [86]:
# Find relationship between city and most common worktype/permit type descr
# Find relationship between city and most common issued_date
# Find relationship between city and declared valuation
#["city","issued_date","declared_valuation","permittypedescr", "worktype"]

In [87]:
common_vals_city = approved_permits[["city","worktype","issued_date","permittypedescr"]].groupby("city").apply(lambda x: x.mode().iloc[0])
common_vals_city.head(55)

,city,worktype,issued_date,permittypedescr
city,,,,
,,LVOLT,2010-01-28 18:14:03+00,Electrical Low Voltage
allston,allston,ELECTRICAL,2012-04-12 19:16:30+00,Short Form Bldg Permit
allston/brighton,allston/brighton,PLUMBING,2011-04-04 19:23:27+00,Plumbing Permit
back,back,OTHER,2010-03-19 13:53:13+00,Short Form Bldg Permit
back bay,back bay,ELECTRICAL,2010-02-24 13:59:43+00,Short Form Bldg Permit
beacon hill,beacon hill,ELECTRICAL,2010-05-03 13:43:31+00,Electrical Temporary Service
boston,boston,ELECTRICAL,2015-12-17 15:08:36+00,Electrical Permit
boston's historic north end,boston's historic north end,NEWCON,2014-05-30 13:13:26+00,Certificate of Occupancy
brighton,brighton,ELECTRICAL,2020-11-24 17:03:13+00,Short Form Bldg Permit
brighton / allston,brighton / allston,ELECTRICAL,2011-02-15 17:46:16+00,Electrical Temporary Service
brighton/allston,brighton/allston,COB,2010-03-04 20:11:16+00,Electrical Permit
charlestown,charlestown,ELECTRICAL,2017-05-02 16:42:52+00,Short Form Bldg Permit
charlestown\=-0,charlestown\=-0,PLUMBING,2012-02-01 15:35:01+00,Plumbing Permit
charleswtown,charleswtown,ELECTRICAL,2010-04-15 21:59:42+00,Certificate of Occupancy
chestnut hill,chestnut hill,PLUMBING,2015-09-01 15:26:38+00,Short Form Bldg Permit
chinatown,chinatown,ELECTRICAL,2010-02-19 19:31:31+00,Electrical Permit
dorchester,dorchester,ELECTRICAL,2022-01-24 13:18:50+00,Short Form Bldg Permit
dorchester (lower mills),dorchester (lower mills),LVOLT,2010-05-14 16:04:18+00,Electrical Low Voltage
dorchester (savin hill),dorchester (savin hill),GAS,2010-11-02 14:16:04+00,Electrical Permit
dorchester center,dorchester center,ELECTRICAL,2021-07-06 14:10:59+00,Gas Permit
dorchester(lower mills),dorchester(lower mills),ELECTRICAL,2011-01-27 18:59:41+00,Electrical Low Voltage
downtown,downtown,LVOLT,2011-02-17 17:14:40+00,Electrical Low Voltage
downtown/financial,downtown/financial,TMPUSOC,2011-11-25 16:46:00+00,Short Form Bldg Permit
downtown/financial district,downtown/financial district,ELECTRICAL,2012-09-20 15:22:30+00,Electrical Permit
e boston,e boston,FA,2009-12-28 14:14:44+00,Electrical Fire Alarms
east,east,ELECTRICAL,2010-02-09 19:49:56+00,Electrical Permit
east boston,east boston,CHGOCC,2010-10-22 14:57:05+00,Long Form/Alteration Permit
east boston,east boston,ELECTRICAL,2011-12-27 17:59:02+00,Short Form Bldg Permit
fenway,fenway,ELECTRICAL,2013-07-24 13:20:21+00,Electrical Permit
fenway/kenmore/audubo,fenway/kenmore/audubo,ELECTRICAL,2010-09-14 15:50:39+00,Electrical Permit
financial district,financial district,ELECTRICAL,2019-07-29 15:36:05+00,Electrical Permit
hyde park,hyde park,ELECTRICAL,2019-04-09 17:35:37+00,Short Form Bldg Permit
jamaica plain,jamaica plain,ELECTRICAL,2014-06-26 16:50:25+00,Short Form Bldg Permit
kenmore/fenway,kenmore/fenway,ELECTRICAL,2011-08-04 19:50:13+00,Electrical Permit
mattapan,mattapan,ELECTRICAL,2022-12-14 17:13:45+00,Short Form Bldg Permit
mission hill,mission hill,ELECTRICAL,2018-03-27 04:00:00+00,Short Form Bldg Permit
north end,north end,ELECTRICAL,2010-04-07 17:10:23+00,Short Form Bldg Permit
northend,northend,ELECTRICAL,2010-03-29 16:02:27+00,Short Form Bldg Permit
ropxbury,ropxbury,SOL,2010-01-22 14:35:23+00,Electrical Permit
roslindale,roslindale,PLUMBING,2023-05-26 13:40:31+00,Short Form Bldg Permit
roxbury,roxbury,ELECTRICAL,2011-12-27 19:18:35+00,Short Form Bldg Permit
roxbury crossin,roxbury crossin,CONVRT,2013-07-16 03:05:18+00,Long Form/Alteration Permit
roxbury crossing,roxbury crossing,ELECTRICAL,2013-05-23 13:34:46+00,Electrical Permit
south,south,ERECT,2013-04-30 18:47:56+00,Certificate of Occupancy
south,south,ELECTRICAL,2010-02-19 20:52:23+00,Electrical Permit
south boston,south boston,ELECTRICAL,2015-08-13 16:03:43+00,Short Form Bldg Permit
south bostonsg,south bostonsg,LVOLT,2012-03-15 14:27:35+00,Electrical Low Voltage
south end,south end,ELECTRICAL,2014-02-25 13:32:20+00,Short Form Bldg Permit
south south boston,south south boston,ERECT,2012-09-20 13:20:46+00,Erect/New Construction
theater district,theater district,ELECTRICAL,2015-07-06 11:44:24+00,Electrical Permit
waterfront,waterfront,PLUMBING,2012-10-26 17:46:08+00,Short Form Bldg Permit
west end,west end,ELECTRICAL,2014-12-03 16:11:45+00,Electrical Permit
west robury,west robury,EXTREN,2023-12-15 15:21:55+00,Short Form Bldg Permit
west roxbry,west roxbry,GAS,2016-04-19 18:24:03+00,Gas Permit
west roxbury,west roxbury,ELECTRICAL,2021-05-24 23:55:17+00,Short Form Bldg Permit

In [88]:
valuation_city = approved_permits[["city","declared_valuation"]].groupby("city").agg("mean")
pd.set_option('display.float_format', '{:.2f}'.format)

valuation_city.head(55)

                             declared_valuation
city
                                      849472.57
allston                               480075.01
allston/brighton                      137325.00
back                                    5000.00
back bay                             1987373.82
beacon hill                            26395.75
boston                                438662.18
boston's historic north end           413871.43
brighton                              270974.82
brighton / allston                      1000.00
brighton/allston                      145311.29
charlestown                           180299.42
charlestown\=-0                          200.00
charleswtown                            3875.00
chestnut hill                          14101.58
chinatown                              37225.71
dorchester                            106118.25
dorchester (lower mills)               36585.61
dorchester (savin hill)                 7937.50
dorchester center                      59903.38
dorchester(lower mills)                 6833.33
downtown                              456383.83
downtown/financial                         0.00
downtown/financial district           276110.22
e boston                                5000.00
east                                   42013.08
east  boston                            2833.67
east boston                           214593.36
fenway                                449416.89
fenway/kenmore/audubo                  54595.27
financial district                     51774.33
hyde park                              45695.11
jamaica plain                          90615.41
kenmore/fenway                          9577.78
mattapan                               43654.02
mission hill                          226730.29
north end                              67666.54
northend                              647905.19
ropxbury                                7443.00
roslindale                             44122.07
roxbury                               252633.13
roxbury crossin                          840.00
roxbury crossing                       54006.25
south                                 214500.00
south                                 117329.46
south boston                          163367.65
south bostonsg                           150.00
south end                              63709.22
south south boston                    500500.00
theater district                       69131.79
waterfront                             24557.04
west end                              311607.69
west robury                            35000.00
west roxbry                             1150.00
west roxbury                           49829.57

In [120]:
#2024
#Importing the dataset
df = pd.read_csv('PropertyAssessmentDatasets/fy2024-property-assessment-data_1_5_2024.csv')

#Cleaning:
df["GROSS_AREA"] = pd.to_numeric(df["GROSS_AREA"], errors='coerce')
df = df.dropna(subset=["GROSS_AREA"])

#Create Groupby
area_city2024 = df[["CITY","GROSS_AREA"]].groupby("CITY").agg("mean")
area_city2024.head()

/var/folders/4h/2q1v376n4mqc0vz5g1f00mbw0000gn/T/ipykernel_1775/2726011543.py:3: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('PropertyAssessmentDatasets/fy2024-property-assessment-data_1_5_2024.csv')

             GROSS_AREA
CITY
ALLSTON         5676.18
BOSTON          7925.42
BRIGHTON        5859.11
BROOKLINE       5606.26
CHARLESTOWN     4055.82

In [121]:
#2023
#Importing the dataset
df = pd.read_csv('PropertyAssessmentDatasets/fy2023-property-assessment-data.csv')

#Cleaning:
df["GROSS_AREA"] = pd.to_numeric(df["GROSS_AREA"], errors='coerce')
df = df.dropna(subset=["GROSS_AREA"])

#Create Groupby
area_city2023 = df[["CITY","GROSS_AREA"]].groupby("CITY").agg("mean")
area_city2023.head()

             GROSS_AREA
CITY
ALLSTON         5664.37
BOSTON          8081.89
BRIGHTON        4619.61
BROOKLINE       5567.83
CHARLESTOWN     4095.37

In [122]:
#2022
#Importing the dataset
df = pd.read_csv('PropertyAssessmentDatasets/fy2022pa-4.csv')

#Cleaning:
df["GROSS_AREA"] = pd.to_numeric(df["GROSS_AREA"], errors='coerce')
df = df.dropna(subset=["GROSS_AREA"])

#Create Groupby
area_city2022 = df[["CITY","GROSS_AREA"]].groupby("CITY").agg("mean")
area_city2022.head()

             GROSS_AREA
CITY
ALLSTON         5371.72
BOSTON          6999.59
BRIGHTON        4353.87
BROOKLINE       5392.44
CHARLESTOWN     3650.75

In [123]:
#2021
#Importing the dataset
df = pd.read_csv('PropertyAssessmentDatasets/data2021-full.csv')

#Cleaning:
df["GROSS_AREA"] = pd.to_numeric(df["GROSS_AREA"], errors='coerce')
df = df.dropna(subset=["GROSS_AREA"])

#Create Groupby
area_city2021 = df[["CITY","GROSS_AREA"]].groupby("CITY").agg("mean")
area_city2021.head()

             GROSS_AREA
CITY
ALLSTON         5296.23
BOSTON          6940.19
BRIGHTON        4321.28
BROOKLINE       5392.39
CHARLESTOWN     3660.09

In [128]:
#2020 - This dataset is weird. Has non MA data
#Importing the dataset
df = pd.read_csv('PropertyAssessmentDatasets/data2020-full.csv')

#Cleaning:
df["GROSS_AREA"] = pd.to_numeric(df["GROSS_AREA"], errors='coerce')
df = df.dropna(subset=["GROSS_AREA"])

#Create Groupby
area_city2020 = df[["MAIL CS","GROSS_AREA"]].groupby("MAIL CS").agg("mean")
area_city2020.head(20)

/var/folders/4h/2q1v376n4mqc0vz5g1f00mbw0000gn/T/ipykernel_1775/2665156489.py:3: DtypeWarning: Columns (6,15,27,28,29,34,35,36,37,38,39,40,41,42,44,45,46,47,48,58,59,64,65,66,67,68,69,70,72,73,74) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('PropertyAssessmentDatasets/data2020-full.csv')

                         GROSS_AREA
MAIL CS
 BOSTON MA                  4395.00
 HINGHAM MA                  485.00
 HONG KONG                  1952.00
 SOUTH  BOSTON MA           1132.00
1016 NICOSIA CYPRUS          756.00
155 SEAPORT BLVD BOSTON      675.00
2111                         799.00
2122                        4960.00
2132                         375.00
44000-NANTES FRANCE          684.00
50132 FIRENZE FI            1004.00
6939105 ISRAEL               695.00
75016 PARIS FRANCE          1571.00
84 STATE ST SUITE              1.00
ABDOVER MA                  1236.00
ABERDEEN NJ                  465.00
ABINGTON MA                 3515.29
ABU DHABI UAE               1078.00
ACCORD MA                   4100.00
ACHSHNET MA                  690.00

In [131]:
#2019
#Importing the dataset
df = pd.read_csv('PropertyAssessmentDatasets/fy19fullpropassess.csv')
df.columns
#Cleaning:
df["GROSS_AREA"] = pd.to_numeric(df["GROSS_AREA"], errors='coerce')
df = df.dropna(subset=["GROSS_AREA"])

#Create Groupby
area_city2019 = df[["MAIL CS","GROSS_AREA"]].groupby("MAIL CS").agg("mean")
area_city2019.head()

/var/folders/4h/2q1v376n4mqc0vz5g1f00mbw0000gn/T/ipykernel_1775/1886166623.py:3: DtypeWarning: Columns (15,60) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('PropertyAssessmentDatasets/fy19fullpropassess.csv')

                      GROSS_AREA
MAIL CS
 WEST  ROXBURY   MA         0.00
1016 NICOSIA CYPRUS       756.00
2132                      375.00
31 DANA AVE STE 3A        889.00
3946 CH-121 GENEVA 3     1638.00

In [5]:
import pandas as pd

files = ["fy2024-property-assessment-data_1_5_2024.csv","fy2023-property-assessment-data.csv","fy2022pa-4.csv", "fy2022pa-4.csv", "data2020-full.csv", "fy19fullpropassess.csv", "property-assessment-fy2017.csv", "ast2018full.csv", "property-assessment-fy2016.csv", "property-assessment-fy2015.csv", "property-assessment-fy2014.csv"]
vals = []
for file in files: 
    df = pd.read_csv('PropertyAssessmentDatasets/' + file)
    vals.append(df.shape[0])

print(min(vals))
print(max(vals))
print(sum(vals))

/var/folders/4h/2q1v376n4mqc0vz5g1f00mbw0000gn/T/ipykernel_16126/2104694504.py:6: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('PropertyAssessmentDatasets/' + file)
/var/folders/4h/2q1v376n4mqc0vz5g1f00mbw0000gn/T/ipykernel_16126/2104694504.py:6: DtypeWarning: Columns (6,15,27,28,29,34,35,36,37,38,39,40,41,42,44,45,46,47,48,58,59,64,65,66,67,68,69,70,72,73,74) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('PropertyAssessmentDatasets/' + file)
/var/folders/4h/2q1v376n4mqc0vz5g1f00mbw0000gn/T/ipykernel_16126/2104694504.py:6: DtypeWarning: Columns (15,60) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('PropertyAssessmentDatasets/' + file)
/var/folders/4h/2q1v376n4mqc0vz5g1f00mbw0000gn/T/ipykernel_16126/2104694504.py:6: DtypeWarning: Columns (60,63) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('PropertyAssessmentDatasets/' + file)
/var/folders/4h/2q1v376n4mqc0vz5g1f00mbw0000gn/T/ipykernel_16126/2104694504.py:6: DtypeWarning: Columns (15,60,63) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('PropertyAssessmentDatasets/' + file)
/var/folders/4h/2q1v376n4mqc0vz5g1f00mbw0000gn/T/ipykernel_16126/2104694504.py:6: DtypeWarning: Columns (60,63) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('PropertyAssessmentDatasets/' + file)

164091
182242
1914941

/var/folders/4h/2q1v376n4mqc0vz5g1f00mbw0000gn/T/ipykernel_16126/2104694504.py:6: DtypeWarning: Columns (15,46,53,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('PropertyAssessmentDatasets/' + file)